[project]
name = "test-task-2025-12-14"
version = "0.1.0"
description = "test-task-2025-12-14"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "fastapi[standard]>=0.124.4",
    "filelock>=3.20.0",
    "psutil>=7.1.3",
    "requests>=2.32.5",
]
